
# .streamlit/config.toml
[theme]
base = "light"
primaryColor = "#d94d14"              # brand orange
backgroundColor = "#FFFFFF"           # white background
secondaryBackgroundColor = "#e9eaeb"  # light grey panels
textColor = "#333333"                 # dark grey text
font = "inter"
